version: '3'
services:
  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hebe_development
    aprrka:
      restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
    - app-network
  web:
    image: ruby:3.1.2
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/app
    environment:
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: pass
      DATABASE_HOST: db
      DATABASE_URL: postgres://myuser:pass@db:5432/hebe_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: