version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: huzurevi_backend_development
    expose:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    image: ruby:3.1.2
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: pass
      DATABASE_HOST: postgres
      DATABASE_URL: postgres://myuser:pass@db:5432/huzurevi_backend_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: