version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: huzurevi_backend_production
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  web:
    build: .
    image: ruby:3.1.2-alpine
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "bundle exec rails db:migrate RAILS_ENV=production && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: pass
      DATABASE_HOST: postgres
      DATABASE_URL: postgres://postgres:pass@db:5432/huzurevi_backend_production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
volumes:
  db_data:
networks:
  mynetwork:
    driver: bridge