
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: myuser
  password: pass

development:
  <<: *default
  database: huzurevi_backend_development

test:
  <<: *default
  database: huzurevi_backend_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
