
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: myuser
  password: pass

development:
  <<: *default
  database: hebe_development

test:
  <<: *default
  database: hebe_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
